# Generated by Django 5.0.7 on 2024-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_businesscontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catch_phrase",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="key_features",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="why_choose",
            field=models.TextField(blank=True, null=True),
        ),
    ]
