# Generated by Django 5.0.7 on 2024-11-22 19:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_catch_phrase_product_key_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="catch_phrase",
            field=ckeditor.fields.RichTextField(default="Default catch phrase text"),
        ),
    ]
