# Generated by Django 5.0.7 on 2024-11-27 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_catch_phrase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(default="Default catch phrase text"),
        ),
        migrations.AlterField(
            model_name="product",
            name="key_features",
            field=ckeditor.fields.RichTextField(default="Default catch phrase text"),
        ),
        migrations.AlterField(
            model_name="product",
            name="why_choose",
            field=ckeditor.fields.RichTextField(default="Default why choose text"),
        ),
    ]
